
// -- user code here --

/* --- start generated code --- */

// Generated by  1.5.0 (Phaser v2.6.2)


/**
 * Swamp_1.
 */
function Swamp_1() {
	
	Phaser.State.call(this);
	
}

/** @type Phaser.State */
var Swamp_1_proto = Object.create(Phaser.State.prototype);
Swamp_1.prototype = Swamp_1_proto;
Swamp_1.prototype.constructor = Swamp_1;

Swamp_1.prototype.init = function () {
	
};

Swamp_1.prototype.preload = function () {
	
};

Swamp_1.prototype.create = function () {
	
};

/* --- end generated code --- */
// -- user code here --
